### ISSUE TITLE
Feed discovery in HTML pages 

### ISSUE THREAD

**Issue by hakimihamdan88** [alexdebril/feed-io#157]
> malformed xml string. parsing error : DOMDocument::loadXML(): Opening and ending tag mismatch: link line 14 and head in Entity, line: 15 (2)

on rss feed http://feeds.feedblitz.com/SethsBlog

but working fine on simplepie http://simplepie.org/demo/?feed=http%3A%2F%2Ffeeds.feedblitz.com%2FSethsBlog

**Comment by alexdebril** [comment]
I got it, there's a trick in Simple Pie that follows the `<link rel="alternate" type="application/atom+xml">` link and parses the REAL feed : http://feeds.feedblitz.com/sethsblog&x=1

Which is working fine with feed-io.

So the real issue here is : feed-io should be able to follow the alternate link if the specified URL is a HTML page.
