### ISSUE TITLE
Problem with invalid urls.

### ISSUE THREAD

**Issue by BrainiacX** [alexdebril/feed-io#166]
Hello, i have a problem with handling invalid links/feeds. I use Feed-io to take feeds by the link given by users, sometimes url can be just not available, sometimes it can be link not on feed , sometimes it can be valid feed but with out items. How should i handle all of this errors? They all return 1 result - error 500 on page. I used try{}catch{}, but when it comes to foreach ($feed as $item)   and "items" is empty [] its just again fall down, but with out exception.

**Comment by alexdebril** [comment]
I think you're facing two different kinds of issues : 

- technical : wrong DNS, 404, 500, or anything else. It throws an exception, so you can catch it and wrap it in a UnavailableFeedException of your own if you want. It will allow you to tell the user "something went wrong with this feed, please try later or check the address"
- functional : empty feed (I'm interested in an example please) for instance. It can be other cases, it's yours to decide

In another application I sometimes get empty feeds, which is normal because I use the LastModifiedSince argument. And in that application, it's not an error : it's just that the feed doesn't have new items.

I hope it helped

**Comment by BrainiacX** [comment]
Hm, with empty feed it was my error, sorry for reporting it.I finally fixed it with try{}catch{} and now can continue accessing next feeds links even if some of them crashed. But than i have question about **timeout** how long Feed-io will try to access the feed link? And is there way to set timeout like 10 seconds, and if its not response-skip it?Thanks for help!
