### ISSUE TITLE
Use content:encoded if an item has no description

### ISSUE THREAD

**Issue by kwebble** [alexdebril/feed-io#188]
Calling `$item->getDescription()` on the items from [this feed](http://feeds.feedburner.com/sciencepalooza-mainfeed?format=xml) returns `NULL`.

In the feed the items include a description in a `<content:encoded>` element. Is there a reason that `getDescription()` does not use that value?

For now I check the result of `getDescription()` and if `NULL` try the `<content:encoded>` value using `$item->getValue('content:encoded')`. But I think it would be useful if feed-io could do that in `getDescription()`.

**Comment by middlebrain** [comment]
This change has an undesired side effect in my application after upgrade ```feedio``` to the current version:

I have to process a feed with both a ```<description>``` and a ```<content:encoded>``` tag but with different values. Bevor this change I could get the content with:
```php
$description = $item->getDescription();
$content = $item->getValue("content:encoded");
```
With this change ```$content``` becomes ```null```.

**Comment by ymc-sise** [comment]
We have the same problem and want to use the `<content:encoded>` value when `getDescription()` is empty.

We use the version 4.9.7. Why is the code ` ->add(new Description(), ['content:encoded'])` missing? If we add the alias to the Standard/RSS.php as in your commit and use `->getContent()` instead of `->getDescription()` it works.

**Comment by ymc-sise** [comment]
Ah well I see https://github.com/alexdebril/feed-io/issues/232

Okay I will use:

`$feedItem->getValue("content:encoded") ?: $feedItem->getContent()`
