### ISSUE TITLE
Use dependency injection over DateBuilder

### ISSUE THREAD

**Issue by romaricdrigon** [alexdebril/feed-io#214]
Hello,

I'm considering upgrading some old script from RssReader 2.0 to FeedIo 4.
We add some custom adaptations needed to handle a lot of different scenarii over feed, one being regarding dates. Some regard dates. At the moment, `FeedIo` does not use dependency injection over `DateTimeBuilder`, an instance is created in the constructor (https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/FeedIo.php#L116). 
Could it be changed? It would make easier to extend/override it, and easier to test.

Thanks!

**Comment by alexdebril** [comment]
Hello,

Yes, you can submit a Pull Request for this. To make things clean the `$dateTimeBuilder` argument would be an optional `DateTimeBuilderInterface` instance and if it's null `FeedIo`FeedIo`'s constructor will create a new `DateTimeBuilder` instance.

I invite you to do so because I don't know when I will be available to push code on feed-io.

Thanks!

**Comment by alexdebril** [comment]
@romaricdrigon this way https://github.com/alexdebril/feed-io/pull/218 ?

**Comment by alexdebril** [comment]
solved in v4.3.8
