### ISSUE TITLE
getLogo() fails?

### ISSUE THREAD

**Issue by jdbiggs** [alexdebril/feed-io#254]
I'm trying to get the logo image for a certain feed and getLogo() is undefined? Am I missing something?

 Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method FeedIo\Feed\Item\Media::getLogo()

**Comment by alexdebril** [comment]
Hi,
It's because you're trying to do it on a `Media` instance, the logo is available only for the `Feed`: https://github.com/alexdebril/feed-io/blob/master/src/FeedIo/Feed.php#L90

Maybe there's something to write in the documentation to avoid such confusion:
- the feed can have a logo, its URL is accessible directly through `getLogo()` method
- an item can have one or more medias, and for each the URL is accessible through `getUrl()`

Tell me if you need more information about this
