### ISSUE TITLE
Is feed-io checking Content-Modified headers properly?

### ISSUE THREAD

**Issue by rscmbbng** [alexdebril/feed-io#258]
Dear developers,

I've recently opened an issue over at NextCloud News considering the huge resource consumption I get from their RSS reader: https://github.com/nextcloud/news/issues/588

As far as I understand it comes down to their reader not checking Content-Modified headers properly, issuing `GET` requests for the whole feed every time rather than `HEAD` requests. 

NextCloud News implements your library so that's why I am also opening an issue here. Hope this is helpful!

**Comment by alexdebril** [comment]
Hi,
This is a big deal even though the patch for the HEAD request won't be. I'll take care of this soon.

**Comment by rscmbbng** [comment]
Hi Alex,

please note that https://github.com/nextcloud/news/issues/588 has been closed, apparently there was a regression in NC News' code.

Thanks and happy new year!

**Comment by alexdebril** [comment]
Thanks !
I made some research to see how to implement this HEAD + GET hits in order to save bandwidth and unfortunately it will introduce some major issues while updating feeds. I got it from reading this: https://github.com/nextcloud/news/issues/607#issuecomment-578522148

The mentioned feed is not using HTTP headers properly, it sets "last-modified" to the current date and time. Another example: https://linuxfr.org/journaux.atom . the header doesn't match the `updated` node, so it's not reliable in that case either. Actually I have many examples of feeds not setting the last-modified header to the last item's date ...

So we can't rely on the HTTP headers. Another approach would be to provide a cache system, which I'm seriously considering.

Thanks anyway for your feedback, feel free to come back to me if you need

**Comment by xmo-odoo** [comment]
@rscmbbng stumbled upon this, logically it's not the client which should check Last-Modified, it should just send them back on the next request and it's the server's job to return a 304. A HEAD + GET would actually *increase* traffic, as the HEAD would either get the same response a GET would (304 on a hit), or it would return a 200 requiring a second request.

However looking a the solarmagazine behaviours it seems to be a bit funky:

* the atom feed has no cache-control (at least when fetching with `curl -I`), so even if a feed reader takes Cache-Control in account it would go and revalidate the resource, this seems unfortunate as the website specifies a 72h max-age
* when getting a 304, solarmagasine doesn't provide a Cache-Control, I do not know whether that impacts anything but it might
