### ISSUE TITLE
Is there a method or way to retrieve rss media file images

### ISSUE THREAD

**Issue by dandruff123** [alexdebril/feed-io#27]
You are doing a great job making this library and it works almost as perfect. When I try retrieving the media files from RSS websites with `$item->getMedias()`, for example:

- http://feeds.skynews.com/feeds/rss/uk.xml places
The files in `FeedIo\Feed\Item\Media` entries, which is very good

- http://rss.cnn.com/rss/edition_europe.rss
- https://www.nasa.gov/rss/dyn/breaking_news.rss

The media files are placed in elements like array elements.

This is my short code that simply prints everything on the screen
`$url="http://feeds.bbci.co.uk/news/world/rss.xml?edition=uk";`
       ` // create a simple FeedIo instance`
        `$feedIo = \FeedIo\Factory::create()->getFeedIo(); `
        `$result = $feedIo->read($url);`
       ` foreach( $result->getFeed() as $item ) { `
                `echo "<pre>".var_export($item->getMedias(),true)."</pre><br>";`
       ` }`

To get the elements you use `$item->getAllElements()` and I get the elements respectively.

Am I doing something wrong or should I retrieve this data differently. I was working with composer to install and use this dependency on Codeigniter 3.0.6. In both cases when I get the media files, I **don't** know how to get the url of each of the entries.
Can you help me with this or maybe make some update to the library on media function like `$this->getMediaUrl()`. 
Thanks

**Comment by alexdebril** [comment]
Hi,

Thank you for your feedback, that's truly supportive !

The medias from the BBCI's feed are defined in <media:thumbnail> tags according to the [Yahoo Media Extension](www.rssboard.org/media-rss) which are not officially supported by feed-io (it supports enclosures).

That's not a big deal because you can catch <media:thumbnails> through the Iterator like this : 

```php
$url="http://feeds.bbci.co.uk/news/world/rss.xml?edition=uk";

// create a simple FeedIo instance
$feedIo = \FeedIo\Factory::create()->getFeedIo();
$result = $feedIo->read($url);
foreach( $result->getFeed() as $item ) {
  $medias = $item->getElementIterator('media:thumbnail');
  foreach( $medias as $media ) {
    var_dump($media->getAttribute('url'));
  }
}
```

Meanwhile, it's not pretty. It enforces you to support Yahoo's extension yourself and I don't think that's what you expect from feed-io. I think there's a way to manage <media:thumbnail> like <enclosure>, I'll patch feed-io for that very soon.

**Comment by dandruff123** [comment]
Thank you for the prompt response. It works and pulls the urls on those sites that support media files. Thanks for sharing.
