### ISSUE TITLE
can't identify Generator or Language

### ISSUE THREAD

**Issue by dingman** [alexdebril/feed-io#362]
Hi! Great package, thank you SO much for it.

I'm trying to collect the `generator` and `language` whenever possible. I looked through the documentation and code, but haven't found any suitable way to do it. Any plans to include something like `getGenerator()` and/or `getLanguage()`?

**Comment by alexdebril** [comment]
Hi @dingman thanks for this feedback, I appreciate it.

On language: it's already there, `FeedInterface::getLanguage()` is supposed to return the feed's language. But because of a mistake I made, you need to use `getValue('language')` instead. I pushed a fix, it will be released soon on both active branches.

On generator: why not, it's a simple tag. However, not so many feeds are providing it so don't expect to see it coming very often. So far, I even never saw it in a feed.

**Comment by dingman** [comment]
@alexdebril Thanks for the update!

Separately, is there a way to build something as a generic function to pull in any custom value?

WordPress by default includes `<generator>` in the feed, which does power 30+% of the Internet, but either might be a good solution.

For example: https://www.jonathan.vc/feed

**Comment by alexdebril** [comment]
@dingman Best way to get the `generator` is to use the API feed-io exposes for extra elements, like this:

```php
$feed->getValue('generator');
```

it's the easiest way for you and it doesn't require to update `feed-io` :)
