### ISSUE TITLE
Item description in RSS feed shows content, not summary

### ISSUE THREAD

**Issue by brotkrueml** [alexdebril/feed-io#392]
When creating an RSS feed and assigning a summary and a content to the item, the content is wrongly used as description instead of the summary.

However, the [RSS 2.0 specification](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt) states:

> description: The item synopsis.

Example:

    $item = new \FeedIo\Feed\Item();
    $item->setSummary('some summary');
    $item->setContent('some content');

Results in:

    <item><description>some content</description></item>

Used version: 5.0.10

**Comment by alexdebril** [comment]
`Summary` is meant for Atom spec, there's no such thing in RSS which exposes only a `description`. And in order to avoid redundancy, the `content` you set in the item will be willingly exposed in the `description` node. 

the best choice here is to forget about RSS and publish your feed through Atom or JSONFeed formats as they both expose a summary and a content. That will be more suitable for your use-case.
