### ISSUE TITLE
URL with formatting specifier in it will result in a warning

### ISSUE THREAD

**Issue by ruudvdd** [alexdebril/feed-io#84]
Hi again,

When I try to read the content of (for example) this URL

> http://feeds.soundcloud.com/users/soundcloud%3ausers:82914291/sounds.rss

I get a warning

> sprintf(): Too few arguments in <path>/vendor/debril/feed-io/src/FeedIo/FeedIo.php on line 344

because the '%3a' in this URL is a valid specifier for the sprintf that'll be used to log.

I think the best solution is to escape the URL _or_ to make logAction accept additional arguments to add to the sprintf and use a specifier at the place you want the URL to be.

What's your opinion on this?

Code to reproduce the problem:

```
$feedIo = new \FeedIo\FeedIo(
    new \FeedIo\Adapter\Guzzle\Client(new \GuzzleHttp\Client()),
    new \Psr\Log\NullLogger()
);

$result = $feedIo->read(
    'http://feeds.soundcloud.com/users/soundcloud%3ausers:82914291/sounds.rss',
    new \FeedIo\Feed()
);
```

**Comment by alexdebril** [comment]
Hi,

Thank you for your feedback. This is a really annoying bug so I just pushed a patch, could you test it and tell me if it works for you please ? I don't have any access to an execution environment right now, that's why I'm asking for this.

I prefer to remove the sprintf call in order to reduce any risk of bugs if the URL contains something I didn't imagined.

Thanks

**Comment by alexdebril** [comment]
Hi again,

I found something with a processor in it, so I finally managed to test my pull request. The bug is fixed and the hotfix is published in a new release.

Thank you

**Comment by ruudvdd** [comment]
Awesome, thank you for fixing it
